# Generated by Django 5.2.6 on 2025-10-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'opportunity')},
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.careeropportunity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.studentprofile'),
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g. 2024-S1, 2024-S2', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('credit_units', models.IntegerField(default=3)),
                ('grade', models.CharField(help_text='Letter grade, e.g. A, A-, B+', max_length=4)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='careers.studentprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
