# Generated by Django 5.2.6 on 2025-10-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.careeropportunity'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='score',
            field=models.FloatField(default=0.0, help_text='Numeric score, e.g. 85.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(default=0.0, help_text='Cumulative GPA across all semesters'),
        ),
    ]
