# Generated by Django 5.2.6 on 2025-10-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_rename_subject_studentgrade_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeropportunity',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='score',
            field=models.FloatField(default=0.0, help_text='Numeric score, e.g. 85.0'),
        ),
    ]
