# Generated by Django 5.2.6 on 2025-10-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_careeropportunity_field_alter_studentgrade_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeropportunity',
            name='field',
            field=models.TextField(blank=True, help_text='Comma-separated required subjects/skills'),
        ),
    ]
