# Generated by Django 5.2.6 on 2025-10-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
