# Generated by Django 5.2.6 on 2025-10-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_generatedreport_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
