# Generated by Django 5.2.6 on 2025-10-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_generatedreport_is_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
