# Generated by Django 5.2.6 on 2025-10-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_remove_generatedreport_downloaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credit_units', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='course_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='careers.courseunit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('name', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester')], max_length=10)),
            ],
            options={
                'unique_together': {('year', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('student', 'course_unit', 'semester')},
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='credit_units',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='subject_name',
        ),
    ]
