# Generated by Django 5.2.6 on 2025-10-27 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_courseunit_studentgrade_course_unit_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='opportunity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='careers.careeropportunity'),
            preserve_default=False,
        ),
    ]
