# Generated by Django 5.2.6 on 2025-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0013_studentgrade_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
