# Generated by Django 5.2.6 on 2025-10-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0014_studentprofile_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='course_unit',
            field=models.CharField(max_length=100),
        ),
    ]
