# Generated by Django 5.2.6 on 2025-10-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0015_alter_studentgrade_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='careers.careeropportunity'),
        ),
    ]
